name: Pull Request Checks

on: pull_request

jobs:
  build:
    name: Build Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [server, cli]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - uses: actions/checkout@v3

    - name: Build
      run: cd ${{ matrix.project }} && go build -v -o bulut-${{ matrix.project }}
  fmt:
    name: Format Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [server, cli]

    steps:
      - uses: actions/checkout@v3

      - uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-path: './${{ matrix.project }}'
          gofmt-flags: '-l -d'
